import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import "./master.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";
import { Header } from "@/components/core/frontend/header/header";
import { Footer } from "@/components/core/frontend/footer/footer";

const nunitoSans = Nunito_Sans({
    variable: "--font-nunito-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${nunitoSans.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <Providers>
                    <div className="flex min-h-dvh flex-col">
                        <Header />
                        <main id="main-content" className="flex-1">
                            {children}
                        </main>
                        <Footer />
                    </div>
                    <Toaster />
                </Providers>
            </body>
        </html>
    );
}
